# Usa una imagen base ligera Slim para cumplir el requisito de optimización
FROM python:3.9-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia los requisitos primero para aprovechar la caché de Docker
COPY requirements.txt .

# Instala dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Copia el resto del código
COPY . .

# Expone el puerto 5000 puerto por defecto de Flask
EXPOSE 5000

# Comando para iniciar la aplicación
CMD ["python", "app.py"]